### ISSUE TITLE
OT and Prometheus with NoopTracer

### ISSUE THREAD

**Issue by jotak** [opentracing-contrib/java-metrics#21]
I tried to setup in kubernetes OT + prometheus in this configuration [1], first without Jaeger. In that scenario with the NoopTracer, application metrics are not exposed to prometheus.

It should probably be able to provide application metrics?

[1] This is a quick setup for demo purpose: https://github.com/jotak/discomon#scenario-with-opentracing

**Comment by jpkrohling** [comment]
I'm closing this, as it appears that it has been fixed already. Feel free to reopen if that's not the case.
