### ISSUE TITLE
Classpath conflicts when using Prometheus & Micrometer

### ISSUE THREAD

**Issue by yurishkuro** [opentracing-contrib/java-metrics#25]
@objectiser I used this in a sample app for today's meetup talk, with Jaeger client and its new Micrometer plugin. I ended up having to exclude the prometheus client transitively pulled by this repo because it was conflicting with the one brought by micrometer:

```xml
        <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-metrics-prometheus</artifactId>
            <version>0.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>io.prometheus</groupId>
                    <artifactId>simpleclient</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by objectiser** [comment]
Thanks for reporting - I have been meaning to switch over to using micrometer instead of directly using prometheus.

**Comment by jpkrohling** [comment]
I'm closing this, as it won't be relevant once Micrometer is used instead of Prometheus.
