### ISSUE TITLE
Switch to Micrometer

### ISSUE THREAD

**Issue by jpkrohling** [opentracing-contrib/java-metrics#26]
@objectiser wrote:
> Currently the https://github.com/opentracing-contrib/java-metrics project provides a prometheus only reporter.
> 
> A micrometer based reporter should be implemented, and the current prometheus reporter deprecated.
> 
> NOTE: the current metric names are specific to the way that prometheus reports histogram data - using three parts representing the 'count', 'sum' and 'buckets'. For micrometer, it may be better to report the data differently in a way that would be consistent across different metric backends - and as a consequence it may be better to use the micrometer API directly rather than having the reporter interface.
>

**Comment by jpkrohling** [comment]
@objectiser should the Spring Auto Configuration for Prometheus use the new Micrometer backend? Or should it also be marked as deprecated, and require the target applications to provide the necessary beans?

**Comment by objectiser** [comment]
@jpkrohling Depends how you want to implement it - the MetricsObserver could directly interface to micrometer cutting out the MetricsReporter abstraction - although that might mean having to worry about deprecating more. And then the metrics observer spring auto config + a suitable micrometer backend in the classpath may be enough.

But if keeping the `MetricsReporter` and providing an alternative micrometer based impl, then I guess have a separate `opentracing-metrics-micrometer-spring-autoconfigure` artifact?

**Comment by jpkrohling** [comment]
@objectiser do you think this can be closed?

**Comment by objectiser** [comment]
Closed by #27
